requirements: update craft-parts to 1.18.1
canonical/rockcraft pull request #191
Opened 2023-02-10 18:32 UTC by cmatsuoka

Craft-parts 1.18.1 fixes ignored file patterns when processing local sources.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2023-02-10 18:35 UTC, lengau approved these changes

2023-02-13 13:39 UTC, tigarmo commented on requirements-dev.txt
> +craft-parts==1.18.1
can you also update `requirements-doc` too please?

2023-02-13 13:40 UTC, tigarmo requested changes
thanks, just needs the requirements-docs update

2023-02-15 19:52 UTC, tigarmo approved these changes

2023-02-16 12:28 UTC, merged