feat(docs): pull in content from craft-parts
canonical/rockcraft pull request #501
Opened 2024-03-06 12:57 UTC by tigarmo

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2024-03-07 12:24 UTC, tigarmo commented on requirements-doc.txt
> +craft-parts @ git+https://github.com/canonical/craft-parts@plugin-doc-details
reminder to fix this

2024-03-07 17:40 UTC, syu-w approved these changes

2024-03-07 17:56 UTC, lengau requested changes
Great job overall!

Could you add an example for the python plugin? Before doing hacky work with classic snaps & python I wouldn't have understood what's needed for getting the dependencies working.

2024-03-08 11:36 UTC, tigarmo commented on docs/.wordlist.txt
This is something else that I want to bundle in the craft-parts docs package too

2024-03-08 11:44 UTC, tigarmo commented on docs/reference/plugins/python_plugin.rst
> +such as ``python3.12-venv`` for projects that use the Deadsnakes ppa.
that's a good idea - added a yaml snippet that includes python 3.12 from deadsnakes

2024-03-08 13:54 UTC, lengau approved these changes
Looks great, thanks!

2024-03-08 13:54 UTC, lengau commented on docs/reference/plugins/python_plugin.rst
> +such as ``python3.12-venv`` for projects that use the Deadsnakes ppa.
Thanks!

2024-03-08 14:54 UTC, merged