docs: apply Menu Engineering to "How-to" pages
canonical/rockcraft pull request #507
Opened 2024-03-11 19:33 UTC by linostar

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

Apply Menu Engineering to "How-to" pages, and use links in landing pages where possible.
Refer to [this example](https://docs.google.com/document/d/1T2aiuVCsF5krBQdqt8Rfaq3gXzhxaypoyetkCSN8RL4/edit#heading=h.5p2vvzpgp6ck) for guidance.

2024-03-13 14:24 UTC, linostar commented
@cjdcordeiro @tigarmo Ready for review.

2024-03-14 16:44 UTC, cjdcordeiro requested changes
The content lgtm. I like the end result.

I wonder if the folder re-organization is needed though...

2024-03-14 16:44 UTC, cjdcordeiro commented on docs/how-to/index.rst
> +how to cut, install and publish slices.
```suggestion
Upgrade your Chisel slicing skills by learning
how to cut, install and publish slices.
```

Let's leave the explanations for the explanations page...it's less error-prone this way

2024-03-18 12:07 UTC, tigarmo approved these changes
Looks pretty good to me! I also like the folder-reorg, it was starting to get very crowded.

2024-03-19 12:51 UTC, tigarmo commented
@linostar can you fix the conflict?

2024-03-19 13:01 UTC, linostar commented
> @linostar can you fix the conflict?

in UK English: done, mate.
in US English: conflict fixer is my middle name.

2024-03-19 13:13 UTC, linostar commented
What's this error in the snap tests? new repo policy?

```
<11>Mar 19 13:05:16 ubuntu: This job has failed to pass a repository policy compliance check as defined in the https://github.com/canonical/repo-policy-compliance repository. The specific failure is listed below. Please update the settings on this project to fix the relevant policy.
<11>Mar 19 13:05:16 ubuntu: authorization comment not found on PR, expected: /canonical/self-hosted-runners/run-workflows 9aea50e9078fb72944c00119113dc052f91dd4a2 - execution not authorized, a comment from a user with write permission or above on the repository approving the workflow was not found on a PR from a fork, the comment should include the string '/canonical/self-hosted-runners/run-workflows <commit SHA>' where the commit SHA is the SHA of the latest commit on the branch, branch_name='ROCKS-1023/docs/apply-menu-engineering-to-howto-pages', commit_sha='9aea50e9078fb72944c00119113dc052f91dd4a2', pull_for_branch.number=507
<11>Mar 19 13:05:16 ubuntu: curl: (22) The requested URL returned error: 403
<11>Mar 19 13:05:16 ubuntu: Stopping execution of jobs due to repository setup is not compliant with policies.
<11>Mar 19 13:05:16 ubuntu: This runner will be stopped or lost, please fix the setup of the repository, then rerun this job.
```

2024-03-19 18:39 UTC, lengau approved these changes
Looks good, thanks!

2024-03-19 19:45 UTC, merged