add a note explaining the sed command
canonical/rockcraft pull request #623
Opened 2024-07-04 04:22 UTC by jdkandersson

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

During user testing I got feedback that it would be nice to explain the `sed` command updating the `base` for the chisel section of the tutorial explaining what the command does.

2024-07-10 11:39 UTC, tigarmo requested changes

2024-07-10 11:39 UTC, tigarmo commented on docs/tutorials/getting-started-with-flask.rst
> +    This tutorial required version ``1.5.2`` or later for Rockcraft. Check the
```suggestion
    This tutorial requires version ``1.5.2`` or later for Rockcraft. Check the
```

2024-07-10 11:39 UTC, tigarmo commented on docs/tutorials/getting-started-with-flask.rst
> +    stable version of Rockcraft.
```suggestion
    stable version.
```

I think this says "version of Rockcraft" enough times to make it clear

2024-07-16 19:32 UTC, lengau approved these changes

2024-08-19 18:12 UTC, SamirPS commented on docs/tutorials/getting-started-with-flask.rst
> +    version of Rockcraft using ``rockcraft --version``. If you have an older
'check your version with ... ' sound better no?

2024-08-19 19:49 UTC, lengau approved these changes

2024-08-20 03:57 UTC, jdkandersson commented on docs/tutorials/getting-started-with-flask.rst
> +    version of Rockcraft using ``rockcraft --version``. If you have an older
Updated

2024-08-20 08:22 UTC, SamirPS approved these changes

2024-08-21 06:43 UTC, cjdcordeiro approved these changes

2024-08-21 06:43 UTC, cjdcordeiro commented on docs/tutorials/getting-started-with-flask.rst
> +    for the ``bare`` base.
```suggestion
    when using the ``bare`` base.
```

2024-08-21 07:25 UTC, jdkandersson commented on docs/tutorials/getting-started-with-flask.rst
> +    for the ``bare`` base.
Updated

2024-08-22 03:58 UTC, jdkandersson commented
@tigarmo it seems that the failed spread tests are unrelated?

2024-08-27 12:55 UTC, merged