docs: update chisel howto guides
canonical/rockcraft pull request #679
Opened 2024-08-26 07:39 UTC by linostar

- [x Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----
This update chisel how-to guides to include details such as the new command `chisel find` and chisel-releases' integrations tests for contributors.

2024-08-26 14:16 UTC, lengau approved these changes
This is a good improvement. I do wonder though whether we should be considering where this whole document belongs compared to https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md

Specifically, this slicing how-to seems more about chisel than about Rockcraft. However, it also seems like chisel doesn't have an equivalent docs site that we could move this to.

2024-08-26 14:16 UTC, lengau commented on docs/how-to/chisel/publish-slice.rst
> +4. Create integration tests to test your changes.
Nice!

2024-08-26 21:08 UTC, medubelko requested changes

2024-08-26 21:08 UTC, medubelko commented on docs/how-to/chisel/publish-slice.rst
> +children folders of ``tests/spread/tests``.
```suggestion
child folders of ``tests/spread/tests``.
```

2024-08-26 21:14 UTC, medubelko commented
> I do wonder though whether we should be considering where this whole document belongs compared to https://github.com/canonical/chisel-releases/blob/main/CONTRIBUTING.md

Medium-term, I'd like all project contributor material to be in README and CONTRIBUTING, and platform/publishing/authoring material in the docs. Does that split make sense for how we've set up chisel?

As for documentation between microprojects, that will have to remain a longer-term concern.

2024-08-27 13:01 UTC, cjdcordeiro approved these changes

2024-08-28 11:54 UTC, tigarmo approved these changes

2024-08-28 17:29 UTC, medubelko approved these changes

2024-08-29 07:43 UTC, linostar commented
@tigarmo This ready for merging. The failing spread tests are due to the problem in LXD waiting for a fix.

2024-08-29 18:24 UTC, merged