lifecycle: use new verbosity levels
canonical/rockcraft pull request #78
Opened 2022-09-20 13:09 UTC by mr-cal

- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

Previously, calling `rockcraft --verbosity=debug` and `rockcraft --verbosity=trace` would fail here.

Referenced from [snapcraft](https://github.com/snapcore/snapcraft/blob/9e10fd1b658df80c35e1996cd92a077e831a8d51/snapcraft/parts/lifecycle.py#L489).

2022-09-20 14:23 UTC, facundobatista requested changes
There is a simpler way!

2022-09-20 14:24 UTC, facundobatista commented on rockcraft/lifecycle.py
> +        cmd.append("--verbosity=trace")
I mean, and replace with that all the if/elif structure...

2022-09-20 17:22 UTC, mr-cal commented on rockcraft/lifecycle.py
> +        cmd.append("--verbosity=trace")
Good idea!
I see you did that in [charmcraft](https://github.com/canonical/charmcraft/blob/a5f200b1a2cdeabf20ce3d72bb4c92012e34b07a/charmcraft/commands/build.py#L321).

I'm going to make a note to do the same in snapcraft too.

2022-09-21 16:07 UTC, facundobatista approved these changes
Wonderful, thanks!

2022-09-21 16:30 UTC, merged